server:
    port: 8888

spring:
    application:
        name: student-device
    datasource:
        url: 'jdbc:h2:mem:inzidb'
        driverClassName: 'org.h2.Driver'
        username: 'inzi'
        password: 'pwd'
    jpa:
        database-platform: 'org.hibernate.dialect.H2Dialect'
    h2:
        console:
            enabled: true
